Rails/blogger/config/routes.rb
Rails.application.routes.draw do
	
  root "articles#index"
  resources :articles do
  	resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only:[:new, :create, :destroy]
  get "login" => "author_sessions#new"
  get "logout" => "author_sessions#destroy"
end

Rails/blogger/app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	has_attached_file :image, styles: {small: "150x150>", med: "250x250>", large: "1000x400>"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/png", "image/jpeg"]

	def tag_list
	self.tags.collect do |tag|
		tag.name
	end.join(", ")
	end

	def tag_list=(tags_string)
  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
  self.tags = new_or_found_tags
end
end

Rails/blogger/app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message:"Should Match Confirmation", if: :password
end

Rails/blogger/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

Rails/blogger/app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
end

Rails/blogger/app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

Rails/blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_filter :require_login, only: [:destroy, :new, :edit]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id 
    @comments = Comment.count
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.save
    flash.notice = "Article '#{@article.title}' Created!"
    redirect_to article_path(@article)
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    flash.notice = "Article '#{@article.title}' Updated!"
    redirect_to article_path(@article)
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash.notice = "Article '#{@article.title}' Delete!"
    redirect_to articles_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end
end

Rails/blogger/app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	def new

	end
	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, notice: "Logged In!")
		else
			flash.now.alert = "Login Failed"
			render action: :new
		end
	end
	def destroy
		logout
		redirect_to(:authors, notice: "Logged Out!")
	end
end

Rails/blogger/app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_filter :require_login
  before_filter :zero_authors_or_authenticated, only:[:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
    end

  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

Rails/blogger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	
	def create
		@comment = Comment.new(comments_params)
		@comment.article_id = params[:article_id]
		@comment.save
		redirect_to article_path(@comment.article)
	end

	def comments_params
		params.require(:comment).permit(:author_name, :body)
	end

	def edit
		
	end

	def update
	    @comment = Comment.find(params[:id])
	    @comment.update(comment_params)
	    redirect_to article_path(@comment.article)
  	end

	def destroy 

	end
end

Rails/blogger/app/controllers/tags_controller.rb
class TagsController < ApplicationController
def show
  @tag = Tag.find(params[:id])
end
end

Rails/blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/blogger/app/helpers/articles_helper.rb
module ArticlesHelper
	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end
end

Rails/blogger/app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

Rails/blogger/app/helpers/authors_helper.rb
module AuthorsHelper
end

Rails/blogger/app/helpers/comments_helper.rb
module CommentsHelper
	
end

Rails/blogger/app/helpers/tags_helper.rb
module TagsHelper
end

Rails/blogger/app/views/articles/_comment.html.erb
<div id="comment">
  <h4 class="comment"> <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted at <%= comment.created_at %></p>
	
</div>

Rails/blogger/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list %>
</p>
  <p>
  <%= f.label :image, "Attach An Image" %><br/>
  <%= f.file_field :image %>
  <p>
    <%= f.submit %>
  </p>
  

<% end %>
<%= link_to 'See Article', @article %> |
<%= link_to 'All Articles', articles_path %>

Rails/blogger/app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render partial: "form" %>

Rails/blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article_path(article), class: 'article_title' %>
    </li>
  <% end %>
</ul>

<% if logged_in? %>
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>
<% end %>

Rails/blogger/app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

Rails/blogger/app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %> |
  <% end %>
</p>
<br/>

<p><%= image_tag(@article.image.url(:large)) %>
<hr/>
<br/>
<p class="body"><%= @article.body %></p>
<br/>
<hr/>
<br/>
<h3>Comments (<%= @article.comments.size %>)</h3>
<%= render partial: 'articles/comment', collection: @article.comments %>
<%= render partial: 'comments/form' %>

<%= link_to 'Back', articles_path %> |
<% if logged_in? %>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), method: :delete, data: {confirm: "Are You Sure?"} %>
<% end %>

Rails/blogger/app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <br/>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>
<br/>
<%= link_to 'Back', articles_path %> |

Rails/blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="flash">
    <%= flash.notice %>
  </p>
  <div id="container">
    <div id="content">
      <%= yield %>
      <hr>
         <h6>
        <% if logged_in? %>
          <%=  current_user.username %>
          <%= link_to "(Logout)", logout_path %>
          <br/><br/>
          <%= link_to "(Admin Panel)", authors_path %>
        <% else %>
        Logged Out
          <%= link_to "(Login)", login_path %>
        <% end %>
      </h6>
    </div>
  </div>
</body>

Rails/blogger/app/views/tags/show.html.erb
<h1> Articles Tagged With "<%= @tag.name.capitalize %>" </h1>

  <ul>
  	<% @tag.articles.each do |article| %>
    <li> <%= link_to article.title, article_path(article) %></li><br/>
  	<% end %>
  </ul>

  <hr/>

<%= link_to 'All Articles', articles_path %> 